[package]
name = "parser_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
serde = "1.0.10"
serde_json = "1.0.2"
serde_derive = "1.0.10"
rust-crypto = "0.2.36"
